=== balaboom123/tw-exam/schemas/compiled-pdf-selection-v1.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://tw-exam.invalid/schemas/compiled-pdf-selection-v1.schema.json",
  "title": "Generated checksum-bound native PDF selection plan",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "parent_SHA256",
    "output_SHA256",
    "output_bytes",
    "operations"
  ],
  "properties": {
    "schema_version": {
      "const": 1
    },
    "parent_SHA256": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$"
    },
    "output_SHA256": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$"
    },
    "output_bytes": {
      "type": "integer",
      "minimum": 1,
      "maximum": 104857600
    },
    "operations": {
      "type": "array",
      "minItems": 1,
      "maxItems": 100000,
      "items": {
        "oneOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "copy_from",
              "length"
            ],
            "properties": {
              "copy_from": {
                "type": "integer",
                "minimum": 0
              },
              "length": {
                "type": "integer",
                "minimum": 1
              }
            }
          },
          {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "literal_base64"
            ],
            "properties": {
              "literal_base64": {
                "type": "string",
                "minLength": 4,
                "contentEncoding": "base64"
              }
            }
          }
        ]
      }
    }
  }
}

=== balaboom123/tw-exam/data/providers/hce_nsysu/native-selections/89f7fed3414028364628aacd046d32925438d9568d5dfae06a66ca1ee80a512e.json
{"operations":[{"literal_base64":"JVBERi0xLjYKJeLjz9MKNjAgMCBvYmoNCjw8L0xlbmd0aCA0NyA+PiA="},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQo2MSAwIG9iag0KPDwvQml0c1BlckNvbXBvbmVudCA4IC9Db2xvclNwYWNlIDIwMSAwIFIgL0ZpbHRlciAvSlBYRGVjb2RlIC9IZWlnaHQgMTc1NCAvTGVuZ3RoIDU2ODU2IC9OYW1lIC9YIC9TdWJ0eXBlIC9JbWFnZSAvVHlwZSAvWE9iamVjdCAvV2lkdGggMTI0MSA+PiA="},{"copy_from":1943808,"length":74},{"literal_base64":"LQgAAAAAAC1qcDJoAAAAFmloZHIAAAbaAAAE2QADBwcBAA=="},{"copy_from":2395840,"length":56768},{"literal_base64":"Cg0KZW5kb2JqDQoyMDEgMCBvYmoNClsvSUNDQmFzZWQgMjQxIDAgUiBdIA0KZW5kb2JqDQoyNDEgMCBvYmoNCjw8L0FsdGVybmF0ZSAvRGV2aWNlUkdCIC9GaWx0ZXIgL0ZsYXRlRGVjb2RlIC9MZW5ndGggMjU3NCAvTiAzID4+IHN0cmVh"},{"copy_from":1408,"length":2589},{"literal_base64":"Cg0KZW5kb2JqDQoyNDQgMCBvYmoNClsvSUNDQmFzZWQgMjQxIDAgUiBdIA0KZW5kb2JqDQozMTAgMCBvYmoNCjw8L0xlbmd0aCA0NyA+PiA="},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQozMTEgMCBvYmoNCjw8L0JpdHNQZXJDb21wb25lbnQgOCAvQ29sb3JTcGFjZSAvRGV2aWNlR3JheSAvRmlsdGVyIC9KUFhEZWNvZGUgL0hlaWdodCAxNzU0IC9MZW5ndGggNzE4NjAgL05hbWUgL1ggL1N1YnR5cGUgL0ltYWdlIC9UeXBlIC9YT2JqZWN0IC9XaWR0aCAxMjQxID4+IA=="},{"copy_from":1943808,"length":125},{"literal_base64":"GEFq"},{"copy_from":1943936,"length":108},{"literal_base64":"RgAG/5PfQhA4DE4gen/VrJGJv8JAEmlvHUeEe4qu2Eaq"},{"copy_from":2453440,"length":71611},{"literal_base64":"Cg0KZW5kb2JqDQozODAgMCBvYmoNCjw8L0xlbmd0aCA0NyA+PiA="},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQozODEgMCBvYmoNCjw8L0JpdHNQZXJDb21wb25lbnQgOCAvQ29sb3JTcGFjZSA1MTUgMCBSIC9GaWx0ZXIgL0pQWERlY29kZSAvSGVpZ2h0IDE3NTQgL0xlbmd0aCA3MDY1MiAvTmFtZSAvWCAvU3VidHlwZSAvSW1hZ2UgL1R5cGUgL1hPYmplY3QgL1dpZHRoIDEyNDEgPj4g"},{"copy_from":1943808,"length":74},{"literal_base64":"LQgAAAAAAC1qcDJoAAAAFmloZHIAAAbaAAAE2QADBwcBAAAAAA9jb2xyAQIBAA=="},{"copy_from":2525632,"length":70552},{"literal_base64":"Cg0KZW5kb2JqDQo1MTUgMCBvYmoNClsvSUNDQmFzZWQgNTU0IDAgUiBdIA0KZW5kb2JqDQo1NTQgMCBvYmoNCjw8L0FsdGVybmF0ZSAvRGV2aWNlUkdCIC9GaWx0ZXIgL0ZsYXRlRGVjb2RlIC9MZW5ndGggMjU3NCAvTiAzID4+IHN0cmVh"},{"copy_from":1408,"length":2589},{"literal_base64":"Cg0KZW5kb2JqDQo1NTcgMCBvYmoNClsvSUNDQmFzZWQgNTU0IDAgUiBdIA0KZW5kb2JqDQo2MzAgMCBvYmoNCjw8L0xlbmd0aCA0NyA+PiA="},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQo2MzEgMCBvYmoNCjw8L0JpdHNQZXJDb21wb25lbnQgOCAvQ29sb3JTcGFjZSAvRGV2aWNlR3JheSAvRmlsdGVyIC9KUFhEZWNvZGUgL0hlaWdodCAxNzU0IC9MZW5ndGggNzY3OTAgL05hbWUgL1ggL1N1YnR5cGUgL0ltYWdlIC9UeXBlIC9YT2JqZWN0IC9XaWR0aCAxMjQxID4+IA=="},{"copy_from":1943808,"length":125},{"literal_base64":"K4Nq"},{"copy_from":1943936,"length":108},{"literal_base64":"RQAG/5PfQhA="},{"copy_from":2596992,"length":76566},{"literal_base64":"Cg0KZW5kb2JqDQo3MDcgMCBvYmoNCjw8L0xlbmd0aCA0NyA+PiA="},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQo3MDggMCBvYmoNCjw8L0JpdHNQZXJDb21wb25lbnQgOCAvQ29sb3JTcGFjZSAvRGV2aWNlR3JheSAvRmlsdGVyIC9KUFhEZWNvZGUgL0hlaWdodCAxNzU0IC9MZW5ndGggNzc4NjYgL05hbWUgL1ggL1N1YnR5cGUgL0ltYWdlIC9UeXBlIC9YT2JqZWN0IC9XaWR0aCAxMjQxID4+IA=="},{"copy_from":1943808,"length":125},{"literal_base64":"L7dq"},{"copy_from":1943936,"length":108},{"literal_base64":"RgAG/5PfQhA4"},{"copy_from":2674240,"length":77641},{"literal_base64":"Cg0KZW5kb2JqDQo3ODcgMCBvYmoNCjw8L0xlbmd0aCA0NyA+PiA="},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQo3ODggMCBvYmoNCjw8L0JpdHNQZXJDb21wb25lbnQgOCAvQ29sb3JTcGFjZSA5MTMgMCBSIC9GaWx0ZXIgL0pQWERlY29kZSAvSGVpZ2h0IDE3NTQgL0xlbmd0aCA4MzcwMiAvTmFtZSAvWCAvU3VidHlwZSAvSW1hZ2UgL1R5cGUgL1hPYmplY3QgL1dpZHRoIDEyNDEgPj4g"},{"copy_from":1943808,"length":74},{"literal_base64":"LQgAAAAAAC1qcDJoAAAAFmloZHIAAAbaAAAE2QADBwc="},{"copy_from":2752448,"length":83616},{"literal_base64":"Cg0KZW5kb2JqDQo5MTMgMCBvYmoNClsvSUNDQmFzZWQgOTUxIDAgUiBdIA0KZW5kb2JqDQo5NTEgMCBvYmoNCjw8L0FsdGVybmF0ZSAvRGV2aWNlUkdCIC9GaWx0ZXIgL0ZsYXRlRGVjb2RlIC9MZW5ndGggMjU3NCAvTiAzID4+IHN0cmVh"},{"copy_from":1408,"length":2589},{"literal_base64":"Cg0KZW5kb2JqDQo5NTQgMCBvYmoNClsvSUNDQmFzZWQgOTUxIDAgUiBdIA0KZW5kb2JqDQoxMDM3IDAgb2JqDQo8PC9MZW5ndGggNDcgPj4g"},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQoxMDM4IDAgb2JqDQo8PC9CaXRzUGVyQ29tcG9uZW50IDggL0NvbG9yU3BhY2UgMTE2MCAwIFIgL0ZpbHRlciAvSlBYRGVjb2RlIC9IZWlnaHQgMTc1NCAvTGVuZ3RoIDg5MjY3IC9OYW1lIC9YIC9TdWJ0eXBlIC9JbWFnZSAvVHlwZSAvWE9iamVjdCAvV2lkdGggMTI0MSA+PiA="},{"copy_from":1943808,"length":74},{"literal_base64":"LQgAAAAAAC1qcA=="},{"copy_from":2836736,"length":89203},{"literal_base64":"Cg0KZW5kb2JqDQoxMTYwIDAgb2JqDQpbL0lDQ0Jhc2VkIDExOTcgMCBSIF0gDQplbmRvYmoNCjExOTcgMCBvYmoNCjw8L0FsdGVybmF0ZSAvRGV2aWNlUkdCIC9GaWx0ZXIgL0ZsYXRlRGVjb2RlIC9MZW5ndGggMjU3NCAvTiAzID4+IHN0cmVh"},{"copy_from":1408,"length":2589},{"literal_base64":"Cg0KZW5kb2JqDQoxMjAwIDAgb2JqDQpbL0lDQ0Jhc2VkIDExOTcgMCBSIF0gDQplbmRvYmoNCjEyODcgMCBvYmoNCjw8L0xlbmd0aCA0NyA+PiA="},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQoxMjg4IDAgb2JqDQo8PC9CaXRzUGVyQ29tcG9uZW50IDggL0NvbG9yU3BhY2UgMTQwNyAwIFIgL0ZpbHRlciAvSlBYRGVjb2RlIC9IZWlnaHQgMTc1NCAvTGVuZ3RoIDgxNjQ5IC9OYW1lIC9YIC9TdWJ0eXBlIC9JbWFnZSAvVHlwZSAvWE9iamVjdCAvV2lkdGggMTI0MSA+PiA="},{"copy_from":1943808,"length":74},{"literal_base64":"LQgAAAAAAC1qcDJoAAAAFmloZHIAAAbaAAAE2QADBwcBAAAAAA9jb2xyAQIBAAAAEAABPn5qcA=="},{"copy_from":2926656,"length":81540},{"literal_base64":"Cg0KZW5kb2JqDQoxNDA3IDAgb2JqDQpbL0lDQ0Jhc2VkIDE0NDMgMCBSIF0gDQplbmRvYmoNCjE0NDMgMCBvYmoNCjw8L0FsdGVybmF0ZSAvRGV2aWNlUkdCIC9GaWx0ZXIgL0ZsYXRlRGVjb2RlIC9MZW5ndGggMjU3NCAvTiAzID4+IHN0cmVh"},{"copy_from":1408,"length":2589},{"literal_base64":"Cg0KZW5kb2JqDQoxNDQ2IDAgb2JqDQpbL0lDQ0Jhc2VkIDE0NDMgMCBSIF0gDQplbmRvYmoNCjE1MzcgMCBvYmoNCjw8L0xlbmd0aCA0NyA+PiA="},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQoxNTM4IDAgb2JqDQo8PC9CaXRzUGVyQ29tcG9uZW50IDggL0NvbG9yU3BhY2UgMTY1NCAwIFIgL0ZpbHRlciAvSlBYRGVjb2RlIC9IZWlnaHQgMTc1NCAvTGVuZ3RoIDg1NzEwIC9OYW1lIC9YIC9TdWJ0eXBlIC9JbWFnZSAvVHlwZSAvWE9iamVjdCAvV2lkdGggMTI0MSA+PiA="},{"copy_from":1943808,"length":74},{"literal_base64":"LQgAAAAAAC1qcDJoAAAAFmloZHIAAAbaAAAE2QADBwcBAAAAAA8="},{"copy_from":3008896,"length":85618},{"literal_base64":"Cg0KZW5kb2JqDQoxNjU0IDAgb2JqDQpbL0lDQ0Jhc2VkIDE2ODkgMCBSIF0gDQplbmRvYmoNCjE2ODkgMCBvYmoNCjw8L0FsdGVybmF0ZSAvRGV2aWNlUkdCIC9GaWx0ZXIgL0ZsYXRlRGVjb2RlIC9MZW5ndGggMjU3NCAvTiAzID4+IHN0cmVh"},{"copy_from":1408,"length":2589},{"literal_base64":"Cg0KZW5kb2JqDQoxNjkyIDAgb2JqDQpbL0lDQ0Jhc2VkIDE2ODkgMCBSIF0gDQplbmRvYmoNCjE3ODcgMCBvYmoNCjw8L0xlbmd0aCA0NyA+PiA="},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQoxNzg4IDAgb2JqDQo8PC9CaXRzUGVyQ29tcG9uZW50IDggL0NvbG9yU3BhY2UgMTkwMSAwIFIgL0ZpbHRlciAvSlBYRGVjb2RlIC9IZWlnaHQgMTc1NCAvTGVuZ3RoIDgyOTAzIC9OYW1lIC9YIC9TdWJ0eXBlIC9JbWFnZSAvVHlwZSAvWE9iamVjdCAvV2lkdGggMTI0MSA+PiA="},{"copy_from":1943808,"length":74},{"literal_base64":"LQgAAAAAAC1qcDJoAAAAFmloZHIAAAbaAAAE2QADBwcBAAAAAA9jb2xyAQIBAAAAEAABQ2RqcA=="},{"copy_from":2926656,"length":135},{"literal_base64":"dNPdF4R7iq7YTQvl/Z661mRi4YCA8MCrvI/MVy6AgICAgICAgPDgZynTopIMz4CAgICA/5AACgABAA=="},{"copy_from":3095424,"length":82601},{"literal_base64":"Cg0KZW5kb2JqDQoxOTAxIDAgb2JqDQpbL0lDQ0Jhc2VkIDE5MzUgMCBSIF0gDQplbmRvYmoNCjE5MzUgMCBvYmoNCjw8L0FsdGVybmF0ZSAvRGV2aWNlUkdCIC9GaWx0ZXIgL0ZsYXRlRGVjb2RlIC9MZW5ndGggMjU3NCAvTiAzID4+IHN0cmVh"},{"copy_from":1408,"length":2589},{"literal_base64":"Cg0KZW5kb2JqDQoxOTM4IDAgb2JqDQpbL0lDQ0Jhc2VkIDE5MzUgMCBSIF0gDQplbmRvYmoNCjIwMzcgMCBvYmoNCjw8L0xlbmd0aCA0NyA+PiA="},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQoyMDM4IDAgb2JqDQo8PC9CaXRzUGVyQ29tcG9uZW50IDggL0NvbG9yU3BhY2UgL0RldmljZUdyYXkgL0ZpbHRlciAvSlBYRGVjb2RlIC9IZWlnaHQgMTc1NCAvTGVuZ3RoIDg2NjAxIC9OYW1lIC9YIC9TdWJ0eXBlIC9JbWFnZSAvVHlwZSAvWE9iamVjdCAvV2lkdGggMTI0MSA+PiA="},{"copy_from":1943808,"length":125},{"literal_base64":"UdZq"},{"copy_from":1943936,"length":108},{"literal_base64":"RQAG/5PfQhA4DE4gen/VrJGJv8JAEmlvHUeEe4qu6L/rWGslZJDQ1w3wwFT/UigSkYCA8MDPsg=="},{"copy_from":3178880,"length":86330},{"literal_base64":"Cg0KZW5kb2JqDQoyMTQwIDAgb2JqDQo8PC9MZW5ndGggNDcgPj4g"},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQoyMTQxIDAgb2JqDQo8PC9CaXRzUGVyQ29tcG9uZW50IDggL0NvbG9yU3BhY2UgL0RldmljZUdyYXkgL0ZpbHRlciAvSlBYRGVjb2RlIC9IZWlnaHQgMTc1NCAvTGVuZ3RoIDc2NTk0IC9OYW1lIC9YIC9TdWJ0eXBlIC9JbWFnZSAvVHlwZSAvWE9iamVjdCAvV2lkdGggMTI0MSA+PiA="},{"copy_from":1943808,"length":125},{"literal_base64":"Kr9q"},{"copy_from":1943936,"length":108},{"literal_base64":"QQAG/5PfQeBErjHytq305qvG77gt1b590iWfFYb4Wn0E"},{"copy_from":3265920,"length":76345},{"literal_base64":"Cg0KZW5kb2JqDQoyMjQ2IDAgb2JqDQo8PC9MZW5ndGggNDcgPj4g"},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQoyMjQ3IDAgb2JqDQo8PC9CaXRzUGVyQ29tcG9uZW50IDggL0NvbG9yU3BhY2UgL0RldmljZUdyYXkgL0ZpbHRlciAvSlBYRGVjb2RlIC9IZWlnaHQgMTc1NCAvTGVuZ3RoIDc3MTYyIC9OYW1lIC9YIC9TdWJ0eXBlIC9JbWFnZSAvVHlwZSAvWE9iamVjdCAvV2lkdGggMTI0MSA+PiA="},{"copy_from":1943808,"length":125},{"literal_base64":"LPdq"},{"copy_from":1943936,"length":108},{"literal_base64":"QgAG/5PfQfBErjHytq305qvG77pEU70XhH2hbBjaq1Oo"},{"copy_from":3342976,"length":76913},{"literal_base64":"Cg0KZW5kb2JqDQoyMzU1IDAgb2JqDQo8PC9MZW5ndGggNDcgPj4g"},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQoyMzU2IDAgb2JqDQo8PC9CaXRzUGVyQ29tcG9uZW50IDggL0NvbG9yU3BhY2UgL0RldmljZUdyYXkgL0ZpbHRlciAvSlBYRGVjb2RlIC9IZWlnaHQgMTc1NCAvTGVuZ3RoIDcyNjIxIC9OYW1lIC9YIC9TdWJ0eXBlIC9JbWFnZSAvVHlwZSAvWE9iamVjdCAvV2lkdGggMTI0MSA+PiA="},{"copy_from":1943808,"length":125},{"literal_base64":"Gzpq"},{"copy_from":1943936,"length":108},{"literal_base64":"QwAG/5PfQfBErjHytq305qvG77o9dKe7YR9oWxgsMbwaxIwROxGN8MA="},{"copy_from":3420608,"length":72364},{"literal_base64":"Cg0KZW5kb2JqDQoyNDY3IDAgb2JqDQo8PC9MZW5ndGggNDcgPj4g"},{"copy_from":2395520,"length":67},{"literal_base64":"Cg0KZW5kb2JqDQoyNDY4IDAgb2JqDQo8PC9CaXRzUGVyQ29tcG9uZW50IDggL0NvbG9yU3BhY2UgL0RldmljZUdyYXkgL0ZpbHRlciAvSlBYRGVjb2RlIC9IZWlnaHQgMTc1NCAvTGVuZ3RoIDI3Mjk3IC9OYW1lIC9YIC9TdWJ0eXBlIC9JbWFnZSAvVHlwZSAvWE9iamVjdCAvV2lkdGggMTI0MSA+PiA="},{"copy_from":1943808,"length":124},{"literal_
